version: "3.8"
services:
  service_a:
    build: ./services/service_a
    ports:
      - "5000:5000"
    depends_on:
      - service_b

  service_b:
    build: ./services/service_b
    ports:
      - "5001:5001"

  service_c:
    build: ./services/service_c
    ports:
      - "5002:5002"
